CREATE TABLE tb_client
(client_id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
name  VARCHAR(50) NOT NULL,
surename  VARCHAR(50) NOT NULL,
postal_code  VARCHAR(50) NOT NULL,
street_name  VARCHAR(50) NOT NULL,
complement  VARCHAR(50) NOT NULL,
district  VARCHAR(50) NOT NULL,
city  VARCHAR(50) NOT NULL,
state  VARCHAR(50) NOT NULL,
created_at DATETIME NOT NULL,
updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
