CREATE TABLE tb_client
(id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
name  VARCHAR(50) NOT NULL,
surename  VARCHAR(50) NOT NULL,
city  VARCHAR(50) NOT NULL,
state  VARCHAR(50) NOT NULL,
created_at DATETIME NOT NULL,
updated_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
